/**
 * Seed de presets básicos — Paso 4.1
 * Ejecutar: npx prisma db seed
 * Solo inserta si no existe (upsert por source+externalId).
 */
import { PrismaClient, FoodSource, DataQuality } from '@prisma/client';

const prisma = new PrismaClient();

const presets = [
  // ─── Proteínas animales ──────────────────────────────────────────────────
  {
    name: 'Chicken Breast (cooked)',
    source: FoodSource.PRESET,
    externalId: 'preset-chicken-breast',
    servingSizeG: 100,
    servingUnit: 'g',
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    sodium: 74,
    qualityStatus: DataQuality.COMPLETE,
  },
  {
    name: 'Ground Beef 80/20 (cooked)',
    source: FoodSource.PRESET,
    externalId: 'preset-ground-beef-80',
    servingSizeG: 100,
    servingUnit: 'g',
    calories: 254,
    protein: 26,
    carbs: 0,
    fat: 17,
    sodium: 75,
    saturatedFat: 6.5,
    qualityStatus: DataQuality.COMPLETE,
  },
  {
    name: 'Salmon (cooked)',
    source: FoodSource.PRESET,
    externalId: 'preset-salmon',
    servingSizeG: 100,
    servingUnit: 'g',
    calories: 208,
    protein: 20,
    carbs: 0,
    fat: 13,
    sodium: 59,
    saturatedFat: 3.1,
    qualityStatus: DataQuality.COMPLETE,
  },
  {
    name: 'Egg (large, whole)',
    source: FoodSource.PRESET,
    externalId: 'preset-egg-whole',
    servingSizeG: 50,
    servingUnit: 'unit',
    calories: 72,
    protein: 6.3,
    carbs: 0.4,
    fat: 5,
    sodium: 71,
    saturatedFat: 1.6,
    qualityStatus: DataQuality.COMPLETE,
  },
  {
    name: 'Egg White',
    source: FoodSource.PRESET,
    externalId: 'preset-egg-white',
    servingSizeG: 33,
    servingUnit: 'unit',
    calories: 17,
    protein: 3.6,
    carbs: 0.2,
    fat: 0.06,
    sodium: 55,
    qualityStatus: DataQuality.COMPLETE,
  },
  {
    name: 'Tuna in Water (canned)',
    source: FoodSource.PRESET,
    externalId: 'preset-tuna-water',
    servingSizeG: 100,
    servingUnit: 'g',
    calories: 116,
    protein: 26,
    carbs: 0,
    fat: 1,
    sodium: 333,
    qualityStatus: DataQuality.COMPLETE,
  },
  {
    name: 'Turkey Breast (cooked)',
    source: FoodSource.PRESET,
    externalId: 'preset-turkey-breast',
    servingSizeG: 100,
    servingUnit: 'g',
    calories: 135,
    protein: 30,
    carbs: 0,
    fat: 1,
    sodium: 70,
    qualityStatus: DataQuality.COMPLETE,
  },
  // ─── Lácteos ─────────────────────────────────────────────────────────────
  {
    name: 'Greek Yogurt (plain, 0%)',
    source: FoodSource.PRESET,
    externalId: 'preset-greek-yogurt-0',
    servingSizeG: 170,
    servingUnit: 'cup',
    calories: 100,
    protein: 17,
    carbs: 6,
    fat: 0.7,
    sodium: 65,
    qualityStatus: DataQuality.COMPLETE,
  },
  {
    name: 'Cottage Cheese (1%)',
    source: FoodSource.PRESET,
    externalId: 'preset-cottage-cheese-1',
    servingSizeG: 113,
    servingUnit: 'cup',
    calories: 81,
    protein: 14,
    carbs: 3.1,
    fat: 1.2,
    sodium: 360,
    qualityStatus: DataQuality.COMPLETE,
  },
  {
    name: 'Whole Milk',
    source: FoodSource.PRESET,
    externalId: 'preset-whole-milk',
    servingSizeG: 244,
    servingUnit: 'cup',
    calories: 149,
    protein: 8,
    carbs: 12,
    fat: 8,
    sodium: 105,
    saturatedFat: 4.6,
    qualityStatus: DataQuality.COMPLETE,
  },
  {
    name: 'Whey Protein Powder',
    source: FoodSource.PRESET,
    externalId: 'preset-whey-protein',
    servingSizeG: 30,
    servingUnit: 'scoop',
    calories: 120,
    protein: 24,
    carbs: 3,
    fat: 1.5,
    sodium: 50,
    qualityStatus: DataQuality.COMPLETE,
  },
  // ─── Carbohidratos ───────────────────────────────────────────────────────
  {
    name: 'White Rice (cooked)',
    source: FoodSource.PRESET,
    externalId: 'preset-white-rice-cooked',
    servingSizeG: 100,
    servingUnit: 'g',
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
    fiber: 0.4,
    sodium: 1,
    qualityStatus: DataQuality.COMPLETE,
  },
  {
    name: 'Brown Rice (cooked)',
    source: FoodSource.PRESET,
    externalId: 'preset-brown-rice-cooked',
    servingSizeG: 100,
    servingUnit: 'g',
    calories: 112,
    protein: 2.3,
    carbs: 23.5,
    fat: 0.8,
    fiber: 1.8,
    sodium: 5,
    qualityStatus: DataQuality.COMPLETE,
  },
  {
    name: 'Oats (dry)',
    source: FoodSource.PRESET,
    externalId: 'preset-oats-dry',
    servingSizeG: 40,
    servingUnit: 'g',
    calories: 148,
    protein: 5.4,
    carbs: 25.7,
    fat: 2.7,
    fiber: 4,
    sodium: 2,
    qualityStatus: DataQuality.COMPLETE,
  },
  {
    name: 'Sweet Potato (cooked)',
    source: FoodSource.PRESET,
    externalId: 'preset-sweet-potato',
    servingSizeG: 100,
    servingUnit: 'g',
    calories: 86,
    protein: 1.6,
    carbs: 20,
    fat: 0.1,
    fiber: 3,
    sodium: 55,
    qualityStatus: DataQuality.COMPLETE,
  },
  {
    name: 'Whole Wheat Bread',
    source: FoodSource.PRESET,
    externalId: 'preset-whole-wheat-bread',
    servingSizeG: 28,
    servingUnit: 'slice',
    calories: 79,
    protein: 4,
    carbs: 15,
    fat: 1.1,
    fiber: 1.9,
    sodium: 132,
    qualityStatus: DataQuality.COMPLETE,
  },
  {
    name: 'White Potato (baked)',
    source: FoodSource.PRESET,
    externalId: 'preset-white-potato-baked',
    servingSizeG: 150,
    servingUnit: 'unit',
    calories: 129,
    protein: 3.4,
    carbs: 29,
    fat: 0.2,
    fiber: 3.2,
    sodium: 14,
    qualityStatus: DataQuality.COMPLETE,
  },
  {
    name: 'Banana',
    source: FoodSource.PRESET,
    externalId: 'preset-banana',
    servingSizeG: 118,
    servingUnit: 'unit',
    calories: 105,
    protein: 1.3,
    carbs: 27,
    fat: 0.4,
    fiber: 3.1,
    sodium: 1,
    sugar: 14,
    qualityStatus: DataQuality.COMPLETE,
  },
  // ─── Grasas y frutos secos ────────────────────────────────────────────────
  {
    name: 'Avocado',
    source: FoodSource.PRESET,
    externalId: 'preset-avocado',
    servingSizeG: 150,
    servingUnit: 'unit',
    calories: 240,
    protein: 3,
    carbs: 13,
    fat: 22,
    fiber: 10,
    sodium: 11,
    saturatedFat: 3.2,
    qualityStatus: DataQuality.COMPLETE,
  },
  {
    name: 'Almonds',
    source: FoodSource.PRESET,
    externalId: 'preset-almonds',
    servingSizeG: 28,
    servingUnit: 'g',
    calories: 164,
    protein: 6,
    carbs: 6.1,
    fat: 14,
    fiber: 3.5,
    sodium: 0,
    saturatedFat: 1.1,
    qualityStatus: DataQuality.COMPLETE,
  },
  {
    name: 'Olive Oil',
    source: FoodSource.PRESET,
    externalId: 'preset-olive-oil',
    servingSizeG: 13.5,
    servingUnit: 'tbsp',
    calories: 119,
    protein: 0,
    carbs: 0,
    fat: 13.5,
    sodium: 0,
    saturatedFat: 1.9,
    qualityStatus: DataQuality.COMPLETE,
  },
  {
    name: 'Peanut Butter',
    source: FoodSource.PRESET,
    externalId: 'preset-peanut-butter',
    servingSizeG: 32,
    servingUnit: 'tbsp',
    calories: 191,
    protein: 7,
    carbs: 7,
    fat: 16,
    fiber: 1.8,
    sodium: 136,
    saturatedFat: 3.3,
    qualityStatus: DataQuality.COMPLETE,
  },
  // ─── Verduras ─────────────────────────────────────────────────────────────
  {
    name: 'Broccoli (raw)',
    source: FoodSource.PRESET,
    externalId: 'preset-broccoli-raw',
    servingSizeG: 100,
    servingUnit: 'g',
    calories: 34,
    protein: 2.8,
    carbs: 6.6,
    fat: 0.4,
    fiber: 2.6,
    sodium: 33,
    qualityStatus: DataQuality.COMPLETE,
  },
  {
    name: 'Spinach (raw)',
    source: FoodSource.PRESET,
    externalId: 'preset-spinach-raw',
    servingSizeG: 30,
    servingUnit: 'cup',
    calories: 7,
    protein: 0.9,
    carbs: 1.1,
    fat: 0.1,
    fiber: 0.7,
    sodium: 24,
    qualityStatus: DataQuality.COMPLETE,
  },
  // ─── Bebidas y cafeína ────────────────────────────────────────────────────
  {
    name: 'Black Coffee (brewed)',
    source: FoodSource.PRESET,
    externalId: 'preset-black-coffee',
    servingSizeG: 240,
    servingUnit: 'cup',
    calories: 2,
    protein: 0.3,
    carbs: 0,
    fat: 0,
    sodium: 5,
    caffeineMg: 95,
    qualityStatus: DataQuality.COMPLETE,
  },
  {
    name: 'Green Tea',
    source: FoodSource.PRESET,
    externalId: 'preset-green-tea',
    servingSizeG: 240,
    servingUnit: 'cup',
    calories: 2,
    protein: 0,
    carbs: 0,
    fat: 0,
    sodium: 2,
    caffeineMg: 28,
    qualityStatus: DataQuality.COMPLETE,
  },
];

async function main() {
  console.log('Seeding presets...');
  let created = 0;
  let skipped = 0;

  for (const preset of presets) {
    const existing = await prisma.food.findFirst({
      where: { source: preset.source, externalId: preset.externalId },
    });

    if (existing) {
      skipped++;
      continue;
    }

    await prisma.food.create({ data: preset as any });
    created++;
  }

  console.log(`Done. Created: ${created}, Skipped (already existed): ${skipped}`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
